version: 0
metadata:
  name: Servo
  description: Servo CI Tasks
  owner: "{{ event.head.user.email }}"
  source: "{{ event.head.repo.url }}"
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "gregarndt/servo:0.1-alpha2"
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd servo && git checkout $GITHUB_HEAD_BRANCH && ./mach test-tidy --no-progress --all"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
    metadata:
      name: Servo test-tidy all
      description: Servo test-tidy all
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "gregarndt/servo:0.1-alpha2"
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd servo && git checkout $GITHUB_HEAD_BRANCH && ./mach test-tidy --no-progress --self-test"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
    metadata:
      name: Servo test-tidy self-test
      description: Servo test-tidy self-test
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    payload:
      maxRunTime: 1200
      image: "gregarndt/servo:0.1-alpha2"
      command:
        - "/bin/bash"
        - "-c"
        - "git clone $GITHUB_HEAD_REPO_URL && cd servo && git checkout $GITHUB_HEAD_BRANCH && ./mach build -d --verbose"
    extra:
      github:
        env: true
        events:
          - pull_request.*
          - push
    metadata:
      name: Servo build
      description: Servo build
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"
