FROM ubuntu:trusty

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    cmake \
    freeglut3-dev \
    gperf \
    libosmesa6-dev \
    libgles2-mesa-dev \
    python-virtualenv \
    xorg-dev \
    ccache \
    libdbus-glib-1-dev \
    libavformat-dev \
    libavcodec-dev \
    libavutil-dev
